### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#1162]
- [x] check bloodASP commits
- [x] merge own changes to gt5u
- [x] check quests
- [x] rewrite large turbines and diesel
- [x] check for loot things in pam and hunger overhaul
- [x] laser engraver deadly beams

**Comment by Bryfer** [comment]
in what way are large turbines rewritten?
Will they start producing more energy? in that case I need an higher tier output or it will explode

**Comment by killslash** [comment]
Add blinding speed to a bee? Or is that not making it in to 1.4? Or has it been done already?

**Comment by Dream-Master** [comment]
will add this in 1.5.0.0

**Comment by Dream-Master** [comment]
@Technus Did you mean the loot tables?

**Comment by Dream-Master** [comment]
We control the lood now with Too Much Loot Mod.
