### ISSUE TITLE
TODO for Update 2.0.2.6

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2357]
- [x] Check this pulls and approve or decline it. (@Technus)
https://github.com/GTNewHorizons/GT5-Unofficial/pull/77
https://github.com/GTNewHorizons/GT5-Unofficial/pull/78
https://github.com/GTNewHorizons/GT5-Unofficial/pull/79
https://github.com/GTNewHorizons/GT5-Unofficial/pull/80

- [x] Fix the Scanner Mod code Code ony throw out %material if meta id is >1000 (@Technus)

- [x] New Oil Drill changes. 
(Everyone want to help me)
  
- [x] Add Gracecraft to MP Server List
(@Dream-Master]

**Comment by Technus** [comment]
Scanner to be tested.

**Comment by Dream-Master** [comment]
Tested and works.
