### ISSUE TITLE
Better Questing 3 backported to 1.7.10, MIT license

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4334]
@funwayguy has graciously backported BQ3 to 1.7.10. 

Evaluate new version of Better Questing, and incorporate our changes

- [ ] #3974 Party mechanics so that parties cannot exploit Coins quests
- [ ] NEI support for BQ
- [ ] #3975 Cannot claim quest rewards (might be a language/keyboard issue?)
- [ ] #3219 #3400 More scrollbar controls
- [ ] #3464 Maybe related to packet reliability between server and client?
- [ ] #4743 BQ causing timeouts when a large number of items picked up due to searching for affected quests

**Comment by bartimaeusnek** [comment]
this requires https://minecraft.curseforge.com/projects/better-questing-quest-book to be updated, aswell as https://minecraft.curseforge.com/projects/themedquestingpack-expansion both mods are ARR therefore harder to update from our side, i got a reply from the first one, but not from the second one.

**Comment by Funwayguy** [comment]
Personally I don't think the themes are too critical to the pack's functionality and you could always whip up a substitute replacement without needing any code (BQ can load them in via resource pack).

Wasn't there also a BloodMagic integration? Not sure if you were using that one.

**Comment by richardhendricks** [comment]
The questbook itself we can probably just remove and tell people via MOTD to use ~ or whatever. One of our early quests basically says that anyways.

As far as I know, we haven't done any BloodMagic integration.  What does that offer?

**Comment by bartimaeusnek** [comment]
BloodMagic integration is MIT Licsensed, therefore we dont need to wait for that, but can update that ourselfes.
