### ISSUE TITLE
2.0.7.3 To-Do-List

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#4474]
Issues that need to be fixed before Update 2.0.7.3

***OPEN ITEMS***
- [ ] #4361 (TecTech) ResearchStation,ObjectHolder and QuantumComputer recipes can only use CrystalProcessorMainframe

***COMPLETED ITEMS***
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4548 Verfiy the BloodArsenal Version (the one that fixes the crash)
- [x] verify ThaumicHorizons Version (indev version)
- [x] verify Gadomancy Version (the one that fixes the on load crash)
- [x] #4231 Fix alumite double tools.
- [x] #4348 Insane H2 production
- [x] #4373 AE2 quest updates
- [x] #3626 Forestry tree breeding quests
- [x] #4473 Fortune 3, mobfarming, other quest tips
- [x] #4465 Filing cabinet tips
- [x] #4468 GT++ debuff ring, new BBQ gloves
- [x] #4459 Rosa Mysteria quest
- [x] #4457 More time to kill quests
- [x] #4133 ferru does not work with GT iron block
- [x] #3851 iskamiunlocked instructions in quest?
- [x] #3513 Planetary Tiers listed in an info quest
- [x] #4267 Tier 8 rocket impossible to obtain
- [x] #4333 **DEFER TO NEXT RELEASE** Makes fusion craftable in 20h instead of 100ish
- [x] #4409 T2 gives back too much tungstensteel
- [x] #4229 Change loot table for God of Thunder crop
- [x] #4324 Change gates for magical energy generators
- [x] #4384 IV mainframe wrong circuit cost
- [x] #4305 Quantium EBF and Vacuum Freezer recipes have the wrong usage.
- [x] #4279 **No fix, visual NEI bug only** Robot Arm crafting is only using Mainframe type circuits
- [x] #4350 UHV Motor is uncraftable 
- [x] #4239 **Wont be fixed in 7.3, its a very deep bug that cant be solved easily** still got a tuctape
- [x] #4107 Gendustry Machine Wrong Comb Requirements, not fixed as of 2.0.7.0
- [x] #4446 Fluid Hatches / Item Busses (only recipes w/o the code change, since the code change requires more work with GUIs.)
- [x] #4303 Oil Sand Dust Recipe
- [x] #4477 Alveary Block Requirements
- [x] #4161 **cant fix yet, will get LowPrio** Fluid lost when transporting fluid from GregTech pipe to EnderIO Conduit
- [x] #3913 **cant fix yet, will get LowPrio** Genetics DataBank Issue
- [x] #4105 **Cannot reproduce** new space bees bug
- [x] #4479 Update server.dat
- [x] #4485 Do not remove bee conversion script this version.  Update warning in core mod next release will remove them.
- [x] #4483 Disable cobblestone boulders in game
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/183 Mega PR for several old fixes
- [x] Update pack version number in coremod. Update warning on Gendustry bees removal.
- [x] #4467 bart's windmill

**Comment by Dream-Master** [comment]
Please add only the important issues not make the list to long otherwise we never get an update :)

**Comment by BlackFlameTNT** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4281
https://github.com/GTNewHorizons/NewHorizons/issues/4267
i can confirm these 2 that need to be changed

**Comment by richardhendricks** [comment]
#4281 is already marked FixedInDev, did you mean a different ticket?

**Comment by 0lafe** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4333
Makes fusion craftable in 20h instead of 100ish
https://github.com/GTNewHorizons/NewHorizons/issues/4409
T2 gens tungsten
https://github.com/GTNewHorizons/NewHorizons/issues/4348
Insane H2 production

**Comment by bedrill64** [comment]
#4229 
#4324 

I'd love to see anything done about these 2, 1st one is just code change, second one requires attention of someone from balance team.

**Comment by botn365** [comment]
#4384

**Comment by SPMoo66** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4305
From what I can tell, the usage for Quantium never got changed. It should be IV tier, I think. Both the EBF and Vacuum Freezer recipes have the wrong usage.

**Comment by Dream-Master** [comment]
Please with check boxes. Thanks
- [ ]

**Comment by yukieiji** [comment]
- [ ] #4279 Robot Arm crafting is only using Mainframe type circuits
- [ ] #4361 ResearchStation,ObjectHolder and QuantumComputer recipes can only use CrystalProcessorMainframe
- [ ] #4350 UHV Motor is uncraftable 
- [ ] #4239 Assembling Machine doesn't accept certain circuits from automation

**Comment by Anarack** [comment]
- [ ] #4107 Gendustry Machine Wrong Comb Requirements, not fixed as of 2.0.7.0

**Comment by bartimaeusnek** [comment]
-[ ] https://github.com/GTNewHorizons/NewHorizons/issues/4446 Fluid Hatches / Item Busses (only recipes w/o the code change, since the code change requires more work with GUIs.)
-[ ] https://github.com/GTNewHorizons/NewHorizons/issues/4303 Oil Sand Dust Recipe

**Comment by Impos913** [comment]
- [ ] #4461 bart's windmill

**Comment by Hakameda** [comment]
If possible https://github.com/GTNewHorizons/NewHorizons/issues/4477

**Comment by draknyte1** [comment]
#4446 doesn't need code changes @bartimaeusnek.
Easier to leave static functions other people use alone and just consider that higher tier buses are useless, but are also crafting components for super buses.. ranging from 16-160 slots a pop.

Super Buses currently have no recipe and will be tiered from EV/IV upwards, where you'd expect larger buses. If someone wanted to come up with said recipes, then we're sorted. ;)

**Comment by draknyte1** [comment]
Would like to fix these today/tomorrow:
https://github.com/alkcorp/GTplusplus/issues/481
https://github.com/alkcorp/GTplusplus/issues/480
https://github.com/alkcorp/GTplusplus/issues/477
https://github.com/alkcorp/GTplusplus/issues/476
https://github.com/alkcorp/GTplusplus/issues/475
https://github.com/alkcorp/GTplusplus/issues/474
https://github.com/alkcorp/GTplusplus/issues/471
https://github.com/alkcorp/GTplusplus/issues/456

**Comment by 0lafe** [comment]
Wasn't the assline oredict circuit issue just visual and you can use the circuits nei just doesn't tell you?

**Comment by BlackFlameTNT** [comment]
it was NEI problem you can use any circuit as far i noticed at 7.0

**Comment by Ethryan** [comment]
How about disabling the surface cobblestone rocks?
https://github.com/GTNewHorizons/NewHorizons/blob/635179d931590d26b9f76d16d901ad24c9bf18f0/config/RWG.cfg#L37

**Comment by yukieiji** [comment]
Could these bugs be fixed before Update 2.0.7.3?
- [ ] #4161 Fluid lost when transporting fluid from GregTech pipe to EnderIO Conduit
- [ ] #3913 Genetics DataBank Issue
- [ ] #4105 new space bees bug

**Comment by 0lafe** [comment]
I think Bart or someone fixed the space bee one

**Comment by richardhendricks** [comment]
@Ethryan File a ticket on that.

**Comment by Ethryan** [comment]
Ticket #4483, filed

**Comment by DoomSquirter** [comment]
want to add I created ticket #4485.  pls hold off on removing or doing whatever you need to to do bee removal.  hold off till later to enact that......

**Comment by richardhendricks** [comment]
ModLoginMessage_Enabled = true;
    ModPackVersion = "2.0.7.3";
    ModHazardousItems_Enabled = false;

    public void onPlayerLogin(PlayerEvent.PlayerLoggedInEvent event)
    {
        event.player.addChatMessage(new ChatComponentText(EnumChatFormatting.GOLD + "=================================================="));
        event.player.addChatMessage(new ChatComponentText(EnumChatFormatting.BOLD + "Welcome to Gregtech:New Horizons " + EnumChatFormatting.GREEN + CoreModConfig.ModPackVersion) );
        event.player.addChatMessage(new ChatComponentText(EnumChatFormatting.RED +  "Please bring comments to " + EnumChatFormatting.BLUE + "https://discord.gg/EXshrPV" ));
        event.player.addChatMessage(new ChatComponentText(EnumChatFormatting.RED +  "WARNING: GENDUSTRY BEE REMOVAL WITH NEXT OFFICIAL RELEASE! THROW YOUR BEES ON THE GROUND TO" ));
        event.player.addChatMessage(new ChatComponentText(EnumChatFormatting.RED +  "WARNING: CONVERT BEES TO GT BEES." ));
        event.player.addChatMessage(new ChatComponentText(EnumChatFormatting.GOLD + "=================================================="));
    }

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/75

**Comment by DietmarKracht** [comment]
We are almost ready for the update 💃

**Comment by Ethryan** [comment]
- [ ] #4231 Fix this, or mark it as fixed.
