### ISSUE TITLE
2.0.8.0 Release Checklist

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4545]
*Need to do*
- [ ] Update coremod version, motd on bees
- [ ] #2269 Fix Lava Creeper overspawning in Nether
- [ ] #2033 #2176 #2324 #4440 #3617 #3229 #4331 #4634 Rebalance Infernal Mobs (multiple tickets), look at wlhlm PR, add dimension restrictions
- [x] #4334 Update to new BQ
- [ ] #4417 Redo GalaticGreg oregen to match GT5u - chunkified and small ore placers.
- [x] #4416 Fix Twilight Forest ore distributions/heights
- [ ] #1715 Thaumcraft Mob Aspects
- [ ] #3051 Try to create a Banker villager
- [ ] #4668 Fix Bee Breeding
- [ ] #4478 Make Bees Great Again (And all associated tickets)
- [ ] #4681 Fix Magic Apiary, make it kickass
- [ ] #4544 Remove Gendustry bees script
- [x] #1974 Fix Nuke EU dupe problem
- [ ] #4201 Finish Migrating page on Wiki to cover moving from one launcher to another
- [x] #4493 Add circuit limiter function to Ore drill to limit radius
- [ ] #2398 Enhanced Build Guide not placing blocks
- [ ] #2465 Powering turrets with GT cables
- [ ] #2506 Thaumcraft recipes needing nerfing/broken
- [ ] #2712 Nerf more Thaumcraft add-on recipes
- [ ] #2518 Foul fume recipe broken
- [ ] #2538 High tier transformers not working correctly
- [ ] #4486 Tinker's Construct materials rebalance
- [ ] #4333 #4335 Superconductor rebalance
- [ ] #4591 Redo DE pre-quests for cores

*Nice to have*
- [ ] #4368 Update seismic prospector ore output, just display orevein chunks
- [ ] #2404 #2523 Universal Fluid Cell (maybe getting removed?) Need to test with volumetric flasks instead, check on recipes requiring Universal cells
- [ ] #4628 Per above, remove universal cells from all quest rewards/requirements.
- [ ] #2514 ExtraCells fluid problem
- [ ] #1817 Drawbridge
- [ ] #2167 Large plasma generator bugs
- [ ] #2246 Pumps and BoP honey
- [ ] #4546 Add chunkloading to GT machines
- [ ] #2557 Make Huge rotors useful somehow
- [ ] #2562 Add Thaumcraft aspects to GTNH custom items
- [ ] #2582 Add support for Forestry saplings to EnderIO farming station
- [ ] #2607 Nanosuit Boots of the Traveller
- [x] #4252 Add Bee Breeding quests
- [ ] #4424 Finish up GT++ quests
- [ ] Repair Forestry Farm regarding not maxed, not optimal, not still growing, harvestable crops

*Low effort or just needs testing/config change*
- [ ] #2482 Fluid in generators/hatches
- [ ] #2441 CESU Craftable in AE
- [ ] #2439 Add brown cable recipe
- [ ] #2387 Add Diamond Spikes to overchanter blacklist
- [ ] #2416 Blacklist for Better Builder's Wands - not preserving owner on warded glass
- [ ] #2560 Test Electric Hoe, make sure it doesn't disappear
- [ ] #2575 Liquid Nitrogen has no texture
- [ ] #2592 Wood fences.  Need testing and possible Chisel group setup for fences
- [ ] #2604 Bronze large boiler not burning heavy oil
- [ ] #2652 TiCon tools in battlegear slots - test with all tools
- [ ] #2699 Packed Ice recipe change in crafting table
- [ ] #2717 Assembly Line books missing localization - needs testing
- [ ] #4491 Make Botany glass properly clear
- [ ] #4434 Test new Java JVM/low perf PC settings
- [ ] #4466 Make sure all IC2 crops are in the wiki
- [ ] #4432 Clean up power generation wiki pages
- [ ] #4372 Incorporate Bedrills IC2 crop notes into wiki
- [ ] #4340 Ore finder rod and GT stone types
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4606 add Radon Recipe to the BioVat
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/3700 re-add Chiseled Arcane Stone

*Finished*
- [x] Capture new Botany glass texture

For staff use only for now.  Once we are closer to release we will open for players to add their wishlist.

**Comment by richardhendricks** [comment]
Using milestones instead, no need to keep this.
