### ISSUE TITLE
2.0.7.4 (New found bugs) To-Do-List

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#4582]
- [x] fix GT compressed Images (revert compresson)
- [x] fix Waterlilly bug in Crops++ again... for some reason it re-appeared
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4587 update GT++
- [x] verfiy/update forestry
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4604 Really Ultimate Battery uncraftable
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4601 UEV Motor uncraftable 
- [x] PR: https://github.com/GTNewHorizons/NewHorizons/pull/4620 Electric Nanosuit Goggles are uncraftable (Damage problems, EMT script)
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4607 Quest Typo
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4610 Log Spam from NEI
- [x] #4608 Hydration cell quest not detected properly - need to make real cell vs NEI?
- [x] #4611 Remove Yellorium comb reward
- [x] #4612 Bees don't need to be pristine, reword quest
- [x] #4613 Fix unlock minor issues
- [x] #4614 Adjust tree breeding quest unlock
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4636 fix Assembly Line Recipes
- [x] #4644 Clay bees fix in GT5U - Fix done, need to step version and include in new release.
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4647 draconium Coils uncraftable
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4653 molecular transformer

**Comment by Hesperusrus** [comment]
Still 2 days

**Comment by DoomSquirter** [comment]
@Hesperusrus   ummm your point being?

**Comment by Dream-Master** [comment]
build lastest source today 4.2.20.0

**Comment by Dream-Master** [comment]
ok only nei issue need to be fixed

**Comment by richardhendricks** [comment]
2.0.7.4 released, closing ticket. NEI spam we will keep an eye on and see if we can duplicate with 2.0.7.4
