### ISSUE TITLE
2.0.7.5 (New found bugs) To-Do-List

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#4676]
- [x] #4610 Log Spam from NEI
- [x] #4678 Compressed solars causing crash on GT power bus
- [x] Update NEI version and rebuild with Mitch's improvements
- [x] Update GT5U version and rebuild with Mitch's improvements.
- [x] Update coremod MOTD banner with new version number
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4690 HP Solar Boiler bugs
