### ISSUE TITLE
Quests Not Working 2.0.8.0

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#5112]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
**The following quests aren't detecting (will add quest ID's when I get my tooltips working):**
_Quest ID, Quest Name, Quest Item, Quest Tab_
- [x] Quest ID 1920 - Can't tell them apart either? (Plant Lens) [Fishing Farming Cooking]
- [x] Quest ID 560-  Railcraft steam power (Solid Fueled Boiler Firebox) [Multiblock Goals]
- [x] Quest ID 559 - Low pressure boiler tank (Low Pressure Boiler Tank) [Multiblock Goals]
- [x] Quest ID 719 - First Breading (Unknown Seeds) [Fishing Farming Cooking]
- [x] Quest ID 725 - Flower Power (Rose Seeds, Dandelion Seeds) [Fishing Farming Cooking]
- [x] Quest ID 561 - Liquid fuelled firebox (Liquid Fueled Boiler Firebox) [Multblock Goals] -- Also quest name is misspelled.
- [x] Quest ID 500 - First things first (Scoop) [How to be(e)]
- [x] Quest ID 92 - You're gonna hate this #4 (Robot Arm (LV)) [Tier 2 - 32 EU (LV)]
- [x] Quest ID 1863 - Throwing out the trash (Voiding Drop Filter) [Tier 2 - 32 EU (LV)]
- [x] Quest ID 699 - Why one coke oven when you can have ten? (Conveyor Module (LV)) [Multiblock Goals]
- [x] Quest ID 116 - Alloy smelter (Basic Alloy Smelter) [Tier 2 - 32 EU (LV)]
- [x] Quest ID 87 - Steel multiblock tanks (Steel Tank Valve, Steel Tank Gauge) [Multiblock Goals]
- [x] Quest ID 540 - A truly sharp saw blade (Diamond Sawblade) [Tier 2 - 32 EU (LV)]
- [x] Quest ID 544 - Compact? Or is it? (Basic Compressor) [Tier 2 - 32 EU (LV)]
- [x] Quest ID 77 - EBF-Time (Electric Blast Furnace, Maintenance Hatch, Muffler Hatch (LV), LV Energy Hatch) [Multiblock Goals]
- [x] Quest ID 578 - The carpenter (Robot Arm (LV)) [Forestry and Multi-farms]
- [x] Quest ID 2121 - Better Grafter through Technology (Branch Cutter) [Forestry and Multi-farms]
- [x] Quest ID 755 - Better than Duct Tape (Soldering Iron) [Multiblock Goals] -- Doesn't detect charged or uncharged.
- [x] Quest ID 1867 - MV Motor (Electric Motor (MV)) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 230 - Your first wand (Iron Capped Wooden Wand) [Novice Thaumaturge]
- [x] Quest ID 896 - You're gonna hate this #3 in MV too (Electric Piston (MV) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 1266 - Low Voltage Transformer (Low Voltage Transformer) [Tier 2 - 32 EU (LV)]
- [x] Quest ID 126 - Electrolysing all the things (Advanced Electrolyzer) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 740 - Extrude all the things (Advanced Extruder) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 1832 - Grinding with Wind (Primitive Kinetic Shaftbox, Windmill) [Multiblock Goals]
- [x] Quest ID 721 - Unknown seeds no more (Basic Scanner) [Fishing Farming Cooking]
- [x] Quest ID 895 - You're gonna hate this #1 in MV too (Conveyor Module (MV)) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 1638 - Electrolyzing water (Basic Electrolyzer) [Project Red]
- [x] Quest ID 944 - Super Tank I (Super Tank I) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 870 - Smelt all the things... (Steam Oven) [Multiblock Goals]
- [x] Quest ID 765 - Time to oil drill! (MV Energy Hatch, Maintenance Hatch) [Multiblock Goals]
- [x] Quest ID 951 - Fluid Solidifier (Advanced Fluid Solidifier) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 1537 - Black and Decker (Wrench (LV), Screwdriver (LV)) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 130 - Portable tanks (Fluid Tank) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 1231 - You gonna hate this 1-4 in HV (Electric Pump (HV), Electric Piston (HV), Conveyor Module (HV), Robot Arm (HV)) [Tier 4 - 512 EU (HV)]
- [x] Quest ID 940 - Cleanroom (Maintenance Hatch, MV Energy Hatch, Filter Machine Casing, Cleanroom Controller) [Multiblock Goals]
- [x] Quest ID 650 - Copter jetpack (Advanced Combustion Generator, Electric Piston (MV)) [Armors and Jetpacks]
- [x] Quest ID 1232 - You gonna hate this 5 and 6 in HV, (Emitter (HV), Sensor (HV)) [Tier 4 - 512 EU (HV)]
- [x] Quest ID 1922 - Transformers, roll out!, (High Voltage Transformer), [Tier 4 - 512 EU (HV)]
- [x] Quest ID 1142 - HV Battery Buffers (High Voltage Battery Buffer - 4 Slot), [Tier 4 - 512 EU (HV)]
- [x] Quest ID 798 - Iron capped Greatwood Wand (Iron Capped Wooden Wand), [Novice Thaumaturge]
- [x] Quest ID 237 - "Stores 50 vis" wand (Gold Banded Greatwood Wand) [Novice Thaumaturge]
- [x] Quest ID 2086 - Grinding heads are better than none, (Diamond Grinding Head) [Tier 3 - 128 EU (MV)]
- [x] Quest ID 1236 - Cutting Machine HV (Advanced Cutting Machine II) [Tier 4 - 512 EU (HV)]
- [ ] Quest ID 933 - Power of the Sun (Solar Panel) [Tier 3 - 128 EU (MV)]

**Quests giving tier inappropriate loot bags:**
_Quest ID, Quest Name, Quest Tab, Description_
- [x] Quest ID 81 - At the end of... [Multiblock Goals] Gives MV bag...should give at least HV bag.
- [ ] Quest ID 990 - Energetic Alloy [Tier 4 - 512 EU (HV)] Gives MV bag...should it give HV bag? Quest also gives T1 coins...should it give at least T2?
- [ ] Quest ID 1526 - Best crossbow? [Tier 4 - 512 EU (HV)] Gives MV bag...should it give HV bag?

**Quests giving tier inappropriate coins:**
_Quest ID, Quest Name, Quest Tab, Description_
- [x] Quest ID 944 - Super Tank I [Tier 3 - 128 EU (MV)] - Gives T1 coins and should give T2
- [x] Quest ID 1324 - Advanced Fluid Extractor [Tier 3 - 128 EU (MV)] - Gives T1 coins and should give T2

**Other quest related issues:**
_Quest ID, Quest Name, Quest Item, Quest Tab, Description_
- [ ] Quest ID 1504 - Divine rod of the gods? (Ore Finder Wand) [Tier 0.5 - Stone Age] doesn't show the NEI crafting recipe when clicked in the quest book.

**Comment by Dream-Master** [comment]
@shawnbyday 
If Quest 725 not works not sure what we can do. i remove all stats allready
Quest 1504 have the problem that the rod have different meta id (active stages) thats why not show up a recipe. Go and search it in nei.

All other Quests fixed

**Comment by shawnbyday** [comment]
I think the errors might be in the localization of the text in the file. I've seen this before in the past. I'm just going to keep adding to this list if that is ok?

**Comment by Dream-Master** [comment]
@shawnbyday I  don't  understand what you mean.

**Comment by shawnbyday** [comment]
![image](https://user-images.githubusercontent.com/33701188/69905593-5408f600-137b-11ea-954e-84fda2520b3d.png)

**Comment by Dream-Master** [comment]
ok will check
