### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#769]
- [x] make all EBF recipes use configuration circuits (the oxy/no oxy issue is still there)
- [x] make all TiCo fluids and containers  have a hint that shows it is useless outside smeltery (like smeltery molten tin cannot be used in gt machines).
- [x] http://jenkins.pc-logix.com/job/OpenSecurity/95/ - update

**Comment by Technus** [comment]
@Dream-Master if u can work on the second one,
i am taking the EBF problem again.

**Comment by Dream-Master** [comment]
@Technus Adding to all fluids in all containers hints are very much work. Are they no easier way to do?

**Comment by Technus** [comment]
You can add hints on the smeltery controller, casting basin/casting table, drains,casting tunnels etc.
the info:
"Some metals processed in smeltery don't meet the purity requirement for GregTech processing"
